repos:
-   repo: https://github.com/keybase/pre-commit-golang
    rev: 314766a2c26b7f32641addbdb0e7e451320ff1f0
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
    -   id: golangci-lint
-   repo: https://github.com/troian/pre-commit-golang
    rev: ab57c5db44bbeeae1031a2e9c2889367f8387d59
    hooks:
    -   id: go-imports
-   repo: https://github.com/syntaqx/git-hooks
    rev: f16f18866390cba642e8af6073ed59504aeada5c
    hooks:
    -   id: go-mod-tidy
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.17.1
    hooks:
    -   id: golangci-lint
